### ISSUE TITLE
1. Goal Setting

### ISSUE THREAD

**Issue by Blue64** [Blue64/Roll20#1]
- [x] #1 I need to set up some Lists and Goals for this GitHub
- [x] #2 I need to set up the Labels
- [x] #3 I need to set up the Projects
- [x] #4 I need to set up the Milestones
- [x] #5 I need to upload the Macros I do have
- [x] #6 I need to direct my helpers to here to get them better involved with the construction
